services:
  - type: web
    name: kildear
    runtime: docker
    repo: https://github.com/dwd-alt/Socset
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mag-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000

databases:
  - name: mag-db
    plan: free
